### ISSUE TITLE
Install openfunction failed

### ISSUE THREAD

**Issue by erdun** [OpenFunction/OpenFunction#139]
Kubectl version
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-18T01:15:06Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/arm64"}
```

How to install openfunction
```
kubectl apply -f https://raw.githubusercontent.com/OpenFunction/OpenFunction/main/config/bundle.yaml

namespace/openfunction created
customresourcedefinition.apiextensions.k8s.io/builders.core.openfunction.io created
customresourcedefinition.apiextensions.k8s.io/clustereventbus.events.openfunction.io created
customresourcedefinition.apiextensions.k8s.io/eventbus.events.openfunction.io created
customresourcedefinition.apiextensions.k8s.io/eventsources.events.openfunction.io created
customresourcedefinition.apiextensions.k8s.io/triggers.events.openfunction.io created
mutatingwebhookconfiguration.admissionregistration.k8s.io/openfunction-mutating-webhook-configuration created
serviceaccount/openfunction-controller-manager created
role.rbac.authorization.k8s.io/openfunction-leader-election-role created
clusterrole.rbac.authorization.k8s.io/openfunction-manager-role created
clusterrole.rbac.authorization.k8s.io/openfunction-metrics-reader created
clusterrole.rbac.authorization.k8s.io/openfunction-proxy-role created
rolebinding.rbac.authorization.k8s.io/openfunction-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/openfunction-manager-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/openfunction-proxy-rolebinding created
configmap/openfunction-manager-config created
service/openfunction-controller-manager-metrics-service created
service/openfunction-webhook-service created
deployment.apps/openfunction-controller-manager created
[unable to recognize "https://raw.githubusercontent.com/OpenFunction/OpenFunction/main/config/bundle.yaml": no matches for kind "Certificate" in version "cert-manager.io/v1", unable to recognize "https://raw.githubusercontent.com/OpenFunction/OpenFunction/main/config/bundle.yaml": no matches for kind "Issuer" in version "cert-manager.io/v1", unable to recognize "https://raw.githubusercontent.com/OpenFunction/OpenFunction/main/config/bundle.yaml": no matches for kind "ClusterBuildStrategy" in version "shipwright.io/v1alpha1"]
Error from server (Invalid): error when creating "https://raw.githubusercontent.com/OpenFunction/OpenFunction/main/config/bundle.yaml": CustomResourceDefinition.apiextensions.k8s.io "functions.core.openfunction.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
Error from server (Invalid): error when creating "https://raw.githubusercontent.com/OpenFunction/OpenFunction/main/config/bundle.yaml": CustomResourceDefinition.apiextensions.k8s.io "servings.core.openfunction.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

**Comment by cheyuexian** [comment]
use v0.6.0 
after kubectl create -f bundle.yaml. still get errors 


#  kubectl create  -f bundle.yaml
namespace/openfunction created
customresourcedefinition.apiextensions.k8s.io/builders.core.openfunction.io created
customresourcedefinition.apiextensions.k8s.io/clustereventbus.events.openfunction.io created
customresourcedefinition.apiextensions.k8s.io/domains.core.openfunction.io created
customresourcedefinition.apiextensions.k8s.io/eventbus.events.openfunction.io created
customresourcedefinition.apiextensions.k8s.io/eventsources.events.openfunction.io created
customresourcedefinition.apiextensions.k8s.io/functions.core.openfunction.io created
customresourcedefinition.apiextensions.k8s.io/servings.core.openfunction.io created
customresourcedefinition.apiextensions.k8s.io/triggers.events.openfunction.io created
serviceaccount/openfunction-controller-manager created
role.rbac.authorization.k8s.io/openfunction-leader-election-role created
clusterrole.rbac.authorization.k8s.io/openfunction-manager-role created
clusterrole.rbac.authorization.k8s.io/openfunction-metrics-reader created
clusterrole.rbac.authorization.k8s.io/openfunction-proxy-role created
rolebinding.rbac.authorization.k8s.io/openfunction-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/openfunction-manager-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/openfunction-proxy-rolebinding created
configmap/openfunction-manager-config created
service/openfunction-controller-manager-metrics-service created
service/openfunction-webhook-service created
deployment.apps/openfunction-controller-manager created
mutatingwebhookconfiguration.admissionregistration.k8s.io/openfunction-mutating-webhook-configuration created
configmap/openfunction-config created
namespace/io created
domain.core.openfunction.io/openfunction created
unable to recognize "bundle.yaml": no matches for kind "Certificate" in version "cert-manager.io/v1"
unable to recognize "bundle.yaml": no matches for kind "Issuer" in version "cert-manager.io/v1"
unable to recognize "bundle.yaml": no matches for kind "ClusterBuildStrategy" in version "shipwright.io/v1alpha1"
unable to recognize "bundle.yaml": no matches for kind "ClusterBuildStrategy" in version "shipwright.io/v1alpha1"
unable to recognize "bundle.yaml": no matches for kind "ClusterBuildStrategy" in version "shipwright.io/v1alpha1"
unable to recognize "bundle.yaml": no matches for kind "ClusterBuildStrategy" in version "shipwright.io/v1alpha1"
