### ISSUE TITLE
[Discussion] Integration possibility of bundled go2sky

### ISSUE THREAD

**Issue by wu-sheng** [OpenFunction/OpenFunction#146]
Hi @FeynmanZhou, I want to set up this thread talking about the tech possibility of bundled go2sky.

FaaS is basically highly distributed, even more complex than micro-services or meshed services. With SkyWalking topology and endpoint dependency, we could visualize the function dependency.

![image](https://user-images.githubusercontent.com/5441976/138855217-46adca57-e3ed-43c2-8003-a3db1ab1fe0b.png)

**Comment by benjaminhuo** [comment]
I've add this to roadmap https://github.com/OpenFunction/OpenFunction/pull/156

**Comment by lizzzcai** [comment]
Hi, I noticed this new roadmap item for openfunction https://github.com/OpenFunction/OpenFunction/pull/156, but it seems like mainly for `Skywalking`. Is it means openfunction will mainly use `Skywalking` for its tracing function? (correct me if i am wrong). 

I saw `OpenTelemetry` was mentioned as well, what is the road map for it? And what is the priority for them?

As a user I am expecting support`OpenTelemetry` standard so that I can use different open source(zipkin, jaeger, tempo etc, probably `skywalking` can be partially supported as well? ) and commercial  software (Dynatrace, Datadog) to trace the function. Thanks.

**Comment by wu-sheng** [comment]
OpenTelemetry and OpenTracing are explained above, which are different from APM. Like dynatrace, they have their native agents, which are much more powerful than just tracing.
This context is general empowering FAAS, not just tracing the calls.

**Comment by lizzzcai** [comment]
Thanks Wu Sheng for your reply. Understood that Skywalking has some unique
features than just tracing, logging and metrics. Like you said above,
probably should separate the opentelemetry into another thread.

**Comment by benjaminhuo** [comment]
We've created an issue https://github.com/OpenFunction/functions-framework/issues/9 for the proposal of integrating tracing with OpenFunction.

**Comment by benjaminhuo** [comment]
The tracing feature needs changes in two separate locations:
- 1. The main repo as described in [the tracing proposal](https://github.com/OpenFunction/OpenFunction/blob/main/docs/proposals/202112_support_function_tracing.md) 
- 2. The skywalking plugin as described in [function framework refactoring](https://github.com/OpenFunction/OpenFunction/blob/main/docs/proposals/202112_functions_framework_refactoring.md) and the refactoring has been done by https://github.com/OpenFunction/functions-framework-go/pull/22

@arugal You can start working on the second item(Skywalking plugin) now. 
I'm not sure if you're interested in working on the first item, if not we can find someone else for the first item.

**Comment by arugal** [comment]
> The tracing feature needs changes in two separate locations:
> 
> * 1. The main repo as described in [the tracing proposal](https://github.com/OpenFunction/OpenFunction/blob/main/docs/proposals/202112_support_function_tracing.md)
> * 2. The skywalking plugin as described in [function framework refactoring](https://github.com/OpenFunction/OpenFunction/blob/main/docs/proposals/202112_functions_framework_refactoring.md) and the refactoring has been done by [functions-framework refactoring functions-framework-go#22](https://github.com/OpenFunction/functions-framework-go/pull/22)
> 
> @arugal You can start working on the second item(Skywalking plugin) now. I'm not sure if you're interested in working on the first item, if not we'll find someone else for the first item.

@benjaminhuo I'm interested in the first item.

**Comment by benjaminhuo** [comment]
That's great!
