### ISSUE TITLE
Make deploy.sh and delete.sh run properly on MacOS

### ISSUE THREAD

**Issue by arugal** [OpenFunction/OpenFunction#152]
I notice that `getopt` is used in both `deploy.sh` and `delete.sh`, but macOS does not support this command by default.
Can we use another solution to replace `getopt`? Such as this:

```bash
while test $# -gt 0
do
  _key="$1"
  case "$_key" in
    --all)
      all=true
      shift
      ;;
    --with-shipwright)
      with_shipwright=true
      shift
      ;;
    --with-knative)
      with_knative=true
      shift
      ;;
    --with-openFuncAsync)
      with_openFuncAsync=true
      shift
      ;;
    -p | --poor-network)
      poor_network=true
      shift
      ;;
    *)
      echo "Internal error!"
      exit 1
      ;;
  esac
  shift
done
```

**Comment by benjaminhuo** [comment]
> I notice that `getopt` is used in both `deploy.sh` and `delete.sh`, but macOS does not support this command by default. Can we use another solution to replace `getopt`? Such as this:
> 
> ```shell
> while test $# -gt 0
> do
>   _key="$1"
>   case "$_key" in
>     --all)
>       all=true
>       shift
>       ;;
>     --with-shipwright)
>       with_shipwright=true
>       shift
>       ;;
>     --with-knative)
>       with_knative=true
>       shift
>       ;;
>     --with-openFuncAsync)
>       with_openFuncAsync=true
>       shift
>       ;;
>     -p | --poor-network)
>       poor_network=true
>       shift
>       ;;
>     *)
>       echo "Internal error!"
>       exit 1
>       ;;
>   esac
>   shift
> done
> ```

Good point, @arugal would you create a PR for this? @wanjunlei @tpiperatgod pls help to review this

**Comment by arugal** [comment]
> @arugal would you create a PR for this?

Yes :)

**Comment by arugal** [comment]
Also, what are the reasons for not delete `cert-manager`in `delete.sh`, can I add an option(`--with-cert-manager`) to delete it? @benjaminhuo

**Comment by benjaminhuo** [comment]
> Also, what are the reasons for not delete `cert-manager`in `delete.sh`, can I add an option(`--with-cert-manager`) to delete it? @benjaminhuo

@tpiperatgod @wanjunlei any idea?

**Comment by tpiperatgod** [comment]
I think we can integrate the `deploy.sh` into the installation step.

The approach is roughly like this: Based on the user's selections, such as node OS, dependencies to be installed, kubernetes version, OpenFunction version, etc., a command is generated, and then the user only needs to execute this command to complete the entire installation process.

**Comment by wanjunlei** [comment]
I think we can use openfunction cli to install all dependencies like dapr. All installation scripts can be integrated into cli.

**Comment by benjaminhuo** [comment]
> I think we can use openfunction cli to install all dependencies like dapr. All installation scripts can be integrated into cli.

Sounds cool if adding this into cli
