### ISSUE TITLE
[Proposal]Optimization of readme

### ISSUE THREAD

**Issue by tpiperatgod** [OpenFunction/OpenFunction#161]
**Proposal**
- Motivation
The current Readme document presents too much content, and I suggest that the content be optimized and triaged to highlight key information.
- Goals
Move references to the website and prioritize samples and user-cases for display
- Example

> \# Logo or Banner
> 
> \# One Sentence Introduction
> 
> ------
> 
> \# Main features or Overview
> 
> \# Samples or Use cases
> 
> \# Getting Started(how to install)
> 
> \# Docs(link to website)
> 
> \# Community(Meeting, Slack, Contributing..)
> 
> \# Code of Conduct

- Action Items
  1. Adjust readme
  2. Adjust website

**Comment by FeynmanZhou** [comment]
+1, I have written a [readme template ](https://github.com/FeynmanZhou/doc_guide/blob/b017ae2873d69e9a2b5cdb1406a3a9ca0351ef3d/readme_guide.md)including recommendations before. Hope it can help our community to refactor the README.

**Comment by tpiperatgod** [comment]
I will refer to this template to optimize the readme of OpenFunction, thx!

**Comment by FeynmanZhou** [comment]
> I will refer to this template to optimize the readme of OpenFunction, thx!

If you optimize it first, I will review and refine it based on your updates.
