### ISSUE TITLE
Updates to the event api do not trigger updates to the function(dapr components)

### ISSUE THREAD

**Issue by tpiperatgod** [OpenFunction/OpenFunction#164]
**Description**
When an event api resource, such as an EventSource resource, is updated, the corresponding dapr components are not updated.

**Environmental**
Tell us what your cluster environment is like, e.g.

- Operating System Information
Ubuntu 18.04 x86_64
- kubernetes version
v1.22.2+k3s2
- OpenFunction version
v0.4.0 and latest
- Versions of dependent components (e.g. dapr, keda, shipwright, knative)
dapr v1.4.0
keda v2.4.0
knative v0.26.0

**Expected behavior**
The current implementation of our Events Framework, i.e. the workload instances of EventSource and Trigger are served by the OpenFunction core api, which means that the reconcile logic of EventSource and Trigger is to generate a Function resource, which manages the dapr component docked to the event source and trigger target.
So when the configuration of the EventSource(or Trigger) changes (e.g. the address of the event source changes, the access account changes), we should expect that the corresponding dapr components will change as well.

**Actual behavior**
When the configuration of the EventSource(or Trigger) has changed (e.g. change of link address of the event source, change of access account), the corresponding dapr components have not changed.

**To Reproduce**

1. Create an EventSource
2. It can be observed that the EventSource function works properly and generates the corresponding dapr components(we can named them of version 1)
3. Make any normal changes to the EventSource(We just want its dapr components to change)
4. After applying this change, it can be observed that the dapr components associated with the EventSource do not change

**Screenshots**

**Additional context**

**Comment by benjaminhuo** [comment]
@zhu733756 would you help to solve this?

**Comment by zhu733756** [comment]
Yeah, if this do not need to fix quickly, I will see these issues after the next week days when I finished fluentd pr.

**Comment by benjaminhuo** [comment]
> Yeah, if this do not need to fix quickly, I will see these issues after the next week days when I finished fluentd pr.

All right
