### ISSUE TITLE
Support to keep the builder after the build is completed

### ISSUE THREAD

**Issue by wanjunlei** [OpenFunction/OpenFunction#168]
**Description**
Support to keep the builder after the build is completed, the user can set how many builders to keep.
Users can set the time for the builder to save and support deleting expired builders automatically.

**Additional context**

**Comment by benjaminhuo** [comment]
> **Description** Support to keep the builder after the build is completed, the user can set how many builders to keep. Users can set the time for the builder to save and support deleting expired builders automatically.
> 
> **Additional context**

So, there are two criteria to purge the old builders: numbers of builders and the expiration time? These two options can be set simultaneously and seperately?

https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/
```
Jobs History Limits 
The .spec.successfulJobsHistoryLimit and .spec.failedJobsHistoryLimit fields are optional. These fields specify how many completed and failed jobs should be kept. By default, they are set to 3 and 1 respectively. Setting a limit to 0 corresponds to keeping none of the corresponding kind of jobs after they finish.
```

**Comment by wanjunlei** [comment]
> 

Yes, these two parameters can be set separately or at the same time, and meeting any one of the conditions will trigger the deletion mechanism when set at the same time.

**Comment by benjaminhuo** [comment]
Souds good
