### ISSUE TITLE
Suggested recommended labels for OpenFunction's components

### ISSUE THREAD

**Issue by tpiperatgod** [OpenFunction/OpenFunction#169]
### Description

Refer to https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/ to add the necessary labels to the components(deployment or pod) of OpenFunction so that it can provide efficient information to the user and can be adapted to some common queries.

For the deployment resource, I think at least the following labels need to be added:
```yaml
    app.kubernetes.io/name: openfunction-controller-manager
    app.kubernetes.io/version: "v0.4.0"
```

**Comment by benjaminhuo** [comment]
Close this with @wanjunlei's PR https://github.com/OpenFunction/OpenFunction/pull/181
