### ISSUE TITLE
镜像找不到啊，好绝望

### ISSUE THREAD

**Issue by Qiaoruiwu** [OpenFunction/OpenFunction#172]
好多国外的镜像dockerhub也找不到，真的实在是找不到，官方能把镜像打包到官方的openfunction 镜像仓库吗

**Comment by benjaminhuo** [comment]
Transfer this issue to main repo and please use English for GitHub communication, Thanks

**Comment by Qiaoruiwu** [comment]
作为一个中国人说中文不是很正常吗？拜托有点中文自信好吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpenFunction/OpenFunction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月8日(星期三) 中午11:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenFunction/OpenFunction] 镜像找不到啊，好绝望 (Issue #172)





 
Transfer this issue to main repo and please use English for GitHub communication, Thanks
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by benjaminhuo** [comment]
This project aims to attract participants from all over the world, so English is better :)
