### ISSUE TITLE
Add ability to control function instance pod min and max number at function schema

### ISSUE THREAD

**Issue by zhaibian** [OpenFunction/OpenFunction#173]
**Description**
There are two scenes need to the ability  to control function instance pod min number.
- First
   Need to scale to zero. 
- Second
   Need to remain some number function instance pod even if this function has not been any called. This scene is very useful for sensitive project which has clod startup 、pulling large image or long time init.

Upon ability can be supported to users who can decide to scale zero or remain min pod number.

The ability  to control function instance pod max number is to protect system security and stability.

**Additional context**
Keda & Knative all have the ability:
keda:  https://keda.sh/docs/2.5/concepts/scaling-deployments/#scaledobject-spec
knative:  https://knative.dev/docs/serving/autoscaling/scale-bounds/

Aliyun FC already has the same ability:
https://help.aliyun.com/document_detail/185038.html#title-570-lbv-4b6

**Comment by benjaminhuo** [comment]
Thanks @zhaibian, this is a very good proposal and we'd like to add this.
@wenchajun would you create a PR for this request?

**Comment by zhaibian** [comment]
> 

Got your idea. This is my thinking:
1. keda can be defined at scaled object spec
2. but knative need to define using annotations ways which openfunction serving has not supported

Even it works, different ways to define the same ability which is not graceful.
Uniform definition ways is better to mask the underlying complexity.

**Comment by benjaminhuo** [comment]
> zhaibian



> > 
> 
> Got your idea. This is my thinking:
> 
> 1. keda can be defined at scaled object spec
> 2. but knative need to define using annotations ways which openfunction serving has not supported
> 
> Even it works, different ways to define the same ability which is not graceful. Uniform definition ways is better to mask the underlying complexity.

Agree, a unified definition to  min/max replicas is needed.
@wenchajun would you write a proposal for this and then create a PR?

**Comment by wenchajun** [comment]
> Agree, a unified definition to min/max replicas is needed.
> @wenchajun would you write a proposal for this and then create a PR?

Ok, I'll finish it.

**Comment by tpiperatgod** [comment]
I would prefer to add a new property to `spec.serving` in function cr to support this feature, as it is a feature of the serving phase.

At the same time, we may also need to consider the design of the annotation section to provide the ability to support new features in an annotated form in the future.

**Comment by wenchajun** [comment]
I have written a proposal, please see https://hackmd.io/A-r2frbVTpiDhpfNc7ac2w. We can discuss and complete it.
