### ISSUE TITLE
Use K8s Gateway API as function's API Gateway

### ISSUE THREAD

**Issue by benjaminhuo** [OpenFunction/OpenFunction#196]
**Description**
K8s gateway API is the next generation of ingress.
It provides some advanced features like [HTTP traffic splitting](https://gateway-api.sigs.k8s.io/v1alpha2/guides/traffic-splitting/), [Cross-Namespace routing](https://gateway-api.sigs.k8s.io/v1alpha2/guides/multiple-ns/), etc. which is powerful and valuable for FaaS as well to be the function's API Gateway.

More info can be found in:
https://gateway-api.sigs.k8s.io/v1alpha2/guides/getting-started/
https://gateway-api.sigs.k8s.io/concepts/api-overview/
https://gateway-api.sigs.k8s.io/implementations/

To support K8s gateway API, we only need to integrate with Gateway API CRDs to be vendor agnostic.

Any implementation that implements K8s gateway API can be plugged into OpenFunction as API Gateway like:
- [Istio](https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/)
- [Contour](https://projectcontour.io/guides/gateway-api/)
- [APISIX](https://github.com/apache/apisix-ingress-controller)
- [Kong](https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/using-gateway-api/)
- [Nginx](https://github.com/nginxinc/nginx-kubernetes-gateway)
- [Envoy Gateway](https://blog.envoyproxy.io/introducing-envoy-gateway-ad385cc59532)

Now both proposal and PR are welcome

**Comment by wanjunlei** [comment]
Ok, I will test it.

**Comment by benjaminhuo** [comment]
@lizzzcai What you're suggesting is very interesting and we can make it happen.

**Comment by benjaminhuo** [comment]
@wrongerror has created this proposal and began to write code.
@rajibmitra is also willing to work on this. so @wrongerror if you have any subtask for this, don't hesitate to create an issue and assign it to @rajibmitra
