### ISSUE TITLE
Replace the architecture diagram with the new design

### ISSUE THREAD

**Issue by FeynmanZhou** [OpenFunction/OpenFunction#214]
Hi team,

Our designer @XiaohuiSept helped us to design a new architecture diagram, how do you think of this new design? If you agree, we will replace the architecture diagram with the new design.

![image](https://user-images.githubusercontent.com/40452856/148922488-dc258a01-96a5-4b16-b380-3ca844184f50.png)

**Comment by benjaminhuo** [comment]
Look good to me!

**Comment by benjaminhuo** [comment]
The sequence of the Events parts could be adjusted to 
```shell
EventSource
Sink
EventBus
Trigger
```

**Comment by FeynmanZhou** [comment]
> The sequence of the Events parts could be adjusted to
> 
> ```shell
> EventSource
> Sink
> EventBus
> Trigger
> ```

Np

**Comment by benjaminhuo** [comment]
We need a SVG format image @FeynmanZhou
