### ISSUE TITLE
Function compilation sources add object storage, etc.

### ISSUE THREAD

**Issue by sunnywa** [OpenFunction/OpenFunction#221]
**Description**
Can openfunction add a feature ？
1、Get the source code from  the object store or some store url for compilation.
2、Get binary files from object storage for image building.

**Additional context**
![image](https://user-images.githubusercontent.com/12031395/149731350-e60f0b85-7728-4c53-bf98-80c6ac9f0eb0.png)

**Comment by benjaminhuo** [comment]
Thanks for the proposal, we'll see what we can do!
Using oss instead of git is for what reasons? both needs network accessibility I think?
Regarding the 2nd point, you mean the source code is already compiled into binaries and put into oss. You need the build process to fetch it and compile it into an image?

**Comment by sunnywa** [comment]
您的邮件我已收到。——王琦

**Comment by FeynmanZhou** [comment]
It looks like Binary to Image and Source to Image in KubeSphere. Does it have strong relevance to OpenFunction?

**Comment by sunnywa** [comment]
We are designing a faas platform based on openfunction。Our platform includes webide, vscode plugin, client-side cli, faas management platform and openfunction, etc.

One of the scenarios is as follows, where the user has a local code development environment and no docker environment. Also their git and openfunction are in two network environments .

![image](https://user-images.githubusercontent.com/12031395/149910847-dfae6914-af82-47c7-842b-821ab36ae7ff.png)


Consider further, the user's code（git） on an intranet server，and have multiple service running environments. Is it necessary to split the build and serving


if I make some mistakes, please point out.
