### ISSUE TITLE
ofn install panic

### ISSUE THREAD

**Issue by yedamao** [OpenFunction/OpenFunction#223]
**Description**
```ofn install --all``` will panic when waiting for the installation to complete
**Environmental**

- Operating System Information
- kubernetes version
- OpenFunction version
- Versions of dependent components (e.g. dapr, keda, shipwright, knative)
```
+------------------+---------+
| COMPONENT        | VERSION |
+------------------+---------+
| CertManager      | 1.5.4   |
| OpenFunction     | 0.5.0   |
| DefaultDomain    | 1.0.1   |
| Dapr             | 1.5.1   |
| IngressNginx     | 1.1.0   |
| Knative Serving  | 1.0.1   |
| Kourier          | 1.0.1   |
| Tekton Pipelines | 0.30.0  |
| Keda             | 2.4.0   |
| Shipwright       | 0.6.1   |
+------------------+---------+
```

**Expected behavior**
installed successfully

**Actual behavior**

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/8220938/150110048-ddb6d071-01b6-4626-8f50-4611c14012f0.png)

**Additional context**

**Comment by tpiperatgod** [comment]
Can you give me information about the OS on which your cluster is based?

like:

linux amd64, ubuntu 18.04 etc.

**Comment by benjaminhuo** [comment]
Looks like is caused by`negative waitgroup counter` @tpiperatgod

**Comment by tpiperatgod** [comment]
> Looks like is caused by`negative waitgroup counter` @tpiperatgod

Yes, I think I know what the problem is

**Comment by tpiperatgod** [comment]
Hi @yedamao , I've fixed this issue and new release will coming soon.

You can use the attached `ofn` or wait for the latest version to be released. And if it still does not work, please feel free to submit any information. 🙂 

[ofn_linux_amd64.tar.gz](https://github.com/OpenFunction/OpenFunction/files/7902955/ofn_linux_amd64.tar.gz)

**Comment by yedamao** [comment]
@tpiperatgod  Thank you! I have installed all components successfully.
