### ISSUE TITLE
Can add a proxy to the ofn command ?

### ISSUE THREAD

**Issue by aBreaking** [OpenFunction/OpenFunction#231]
I have configured a local 1080 proxy, but I still cannot install it successfully 
```
$ ofn install --all 

The following existing components will be skipped:
        - Knative Serving
        - Tekton Pipelines
        - Keda
 ✗ Dapr - Stopped!
 ✗ Shipwright - Stopped!
 ✗ Cert Manager - Stopped!
 ✗ Ingress - Failed!
 ⇲ Error reports: 
Failed to install Ingress: 
Unable to connect to the server: read tcp 192.168.80.130:59322->185.199.109.133:443: read: connection reset by peer
: exit status 1
``` 

Or my proxy configuration is wrong? my proxy configuration :

```
export http_proxy="http://192.168.80.1:1080"
export https_proxy="http://192.168.80.1:1080"
```

**Comment by tpiperatgod** [comment]
It seems that the proxy is working, but it is not accessible?

**Comment by aBreaking** [comment]
@tpiperatgod my fault.  by tracing network proxy .  I suddenly realized that i have configuration proxy, but forgot configuration no_proxy.  so add `export no_proxy="192.168.."` . it`s working , thx
