### ISSUE TITLE
Add global configuration for OpenFunction

### ISSUE THREAD

**Issue by tpiperatgod** [OpenFunction/OpenFunction#242]
**Description**
We need to add a global configuration for OpenFunction's controller-manager, such as the plugin configuration, the configuration of other components, and so on. 

We can use the configMap resource to implement this feature.

**Additional context**
example:

```yaml
apiVersion: v1
data:
  # Tell OpenFunction the namespace where knative-serving is located
  knative-serving.namespace: "knative-serving"
  # Tell OpenFunction the name of the ConfigMap of the knative-serving's configuration
  knative-serving.config-features.name: "config-features"
  # Configuration of the tracing of functions
  plugins.tracing: |
    # Switch for tracing, default to false
    enabled: false
    # Provider name can be set to "skywalking", "opentelemetry"
    # A valid provider must be set if tracing is enabled.
    provider:
      name: "skywalking"
      oapServer: "localhost:xxx"
    # Custom tags to add to tracing
    tags:
      func: function-with-tracing
      layer: faas
      tag1: value1
      tag2: value2
    baggage:
    # baggage key is `sw8-correlation` for skywalking and `baggage` for opentelemetry
    # Correlation context for skywalking: https://skywalking.apache.org/docs/main/latest/en/protocols/skywalking-cross-process-correlation-headers-protocol-v1/
    # baggage for opentelemetry: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/baggage/api.md
    # W3C Baggage Specification/: https://w3c.github.io/baggage/
      key: sw8-correlation # key should be baggage for opentelemetry
      value: "base64(string key):base64(string value),base64(string key2):base64(string value2)"
  # Configuration of the order of the plugins
  plugins: |
    pre:
    - plugin-custom
    - plugin-example
    post:
    - plugin-custom
    - plugin-example
kind: ConfigMap
metadata:
  creationTimestamp: "2022-03-06T10:46:38Z"
  labels:
    app.kubernetes.io/version: v0.5.0
  name: openfunction-config
  namespace: openfunction
  resourceVersion: "85553282"
  uid: fb6bfa6f-b50a-420a-8027-67af4bf3b395
```

**Comment by weiqiang-w** [comment]
i have no idea about this when i use skywalking when deploy a new function

configMap:
apiVersion: v1
data:
  knative-serving.config-features.name: config-features
  knative-serving.namespace: knative-serving
  openfunction.dapr-proxy.image: openfunction/dapr-proxy:v0.1.1
  openfunction.eventsource-handler.image: openfunction/eventsource-handler:v4
  openfunction.trigger-handler.image: openfunction/trigger-handler:v4
  plugins.tracing: |
    enabled: true
    provider:
      name: "skywalking"
      oapServer: "skywalking-skywalking-helm-oap:11800"
    tags:
      func: function-with-tracing
      layer: faas
      tag1: value1
      tag2: value2
    baggage:
      key: sw8-correlation
      value: "base64(string key):base64(string value),base64(string key2):base64(string value2)"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: openfunction
    meta.helm.sh/release-namespace: openfunction
  creationTimestamp: "2023-04-18T09:11:27Z"
  labels:
    app.kubernetes.io/instance: openfunction
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: openfunction
    app.kubernetes.io/version: v1.0.0
    helm.sh/chart: openfunction-0.5.0
  name: openfunction-config
  namespace: openfunction
  resourceVersion: "85178393"




java.lang.IllegalArgumentException: unknown tracing provider (null, skywalking-skywalking-helm-oap:11800)
        at dev.openfunction.invoker.context.RuntimeContext.loadPlugins(RuntimeContext.java:95)
        at dev.openfunction.invoker.context.RuntimeContext.<init>(RuntimeContext.java:82)
        at dev.openfunction.invoker.Runner.main(Runner.java:65)

@tpiperatgod

**Comment by tpiperatgod** [comment]
Hi @wanjunlei , can you help look at this...

**Comment by wanjunlei** [comment]
@weiqiang-w The java framework does not support skywalking now.

**Comment by weiqiang-w** [comment]
@wanjunlei  Will the official have a schedule to support the java framework on SKYWALKING ??

**Comment by wanjunlei** [comment]
Yes, the java framework will support skywalking later.
