### ISSUE TITLE
can't connect the docker-registry when use http

### ISSUE THREAD

**Issue by hurricane1988** [OpenFunction/OpenFunction#250]
We use the private docker registry and already config the "insecure-registries" of /etc/docker/daemon.json. But it will connect docker registry with https, any help please?

**Comment by benjaminhuo** [comment]
@hurricane1988 Any contribution is welcomed! Are u in our wechat group?

![image](https://user-images.githubusercontent.com/18525465/159283269-fee2bdcc-bcaa-43bb-92a2-ff0ebf004895.png)

**Comment by benjaminhuo** [comment]
duplicated with https://github.com/OpenFunction/OpenFunction/issues/249
