### ISSUE TITLE
Let functions be triggered by GitHub events

### ISSUE THREAD

**Issue by tpiperatgod** [OpenFunction/OpenFunction#254]
**Proposal**

- Motivation

  GitHub is a mainstream code repository, and many developers choose to push their project on GitHub. To meet the needs of the CI\CD of the users, GitHub provides [Webhooks and events](https://docs.github.com/en/developers/webhooks-and-events).

  OpenFunction's event framework is dedicated to improving OpenFunction's event responsiveness, so I thought it would be useful to introduce a solution for triggering OpenFunction functions from GitHub events.

- Goals

  OpenFunction functions can be triggered by GitHub events.

- Example

  In this case, it was necessary to introduce [Argo Events](https://argoproj.github.io/argo-events/), which supports rich event sources, and push Github events to Nats Streaming via Argo Events' [GitHub EventSource](https://argoproj.github.io/argo-events/eventsources/setup/github/).

  After that, the OpenFunction Events Trigger, which is subscribed to Nats Streaming, can fetch GitHub events from it and wake up the OpenFunction functions to handle GitHub events.

  ![Schematic diagram](https://user-images.githubusercontent.com/2360535/159641207-4c94b90b-49c4-4567-ba2f-428b7962f019.png)

- Action Items

  - Setup Argo Events
  - Create a GitHub EventSource in Argo Events
  - Create an Ingress to expose the EventSource service
  - Configure the GitHub webhook to use the Ingress address as the callback address
  - Docking OpenFunction Events EventBus with Nats Streaming enables OpenFunction Events Trigger to read events from Nats Streaming

**Comment by lizzzcai** [comment]
Hi @tpiperatgod , this is something I am looking for as well, I check with Shipwright team yesterday https://github.com/shipwright-io/build/issues/1017 and actually they are trying to support it. You can check this: https://github.com/shipwright-io/community/pull/68

**Comment by benjaminhuo** [comment]
> Hi @tpiperatgod , this is something I am looking for as well, I check with Shipwright team yesterday [shipwright-io/build#1017](https://github.com/shipwright-io/build/issues/1017) and actually they are trying to support it. You can check this: [shipwright-io/community#68](https://github.com/shipwright-io/community/pull/68)
> 
> But seems like they only support tekton, trigger by `Argo` is something I am looking for.

@wanjunlei can keep an eye on shipwright's plan like [shipwright-io/community#68](https://github.com/shipwright-io/community/pull/68)

**Comment by benjaminhuo** [comment]
argo events is one option, 
Can we add some event source to OpenFunction's own events instead of using argo events?

**Comment by benjaminhuo** [comment]
Close this for now because we're going to add OpenFunction's own github/gitlab event source as described in https://github.com/OpenFunction/OpenFunction/issues/303
