### ISSUE TITLE
How to track with skywalking in dapr

### ISSUE THREAD

**Issue by xonze** [OpenFunction/OpenFunction#255]
**Description**
I tested the skywalking plug-in in function for tracking, but I can't trace the requests in dapr, which is a pity

**Comment by tpiperatgod** [comment]
Hi @xonze , I think this [PR](https://github.com/OpenFunction/functions-framework-go/pull/45) will solve your problem and I will add a tracing sample soon. The latest version of functions-framework-go is `v0.2.2`.

**Comment by tpiperatgod** [comment]
Hi @xonze here is the tracing sample: https://github.com/OpenFunction/samples/blob/main/functions/tracing/README.md

pls let me know if it can solve your problem, thx.

**Comment by xonze** [comment]
> Hi @xonze here is the tracing sample: https://github.com/OpenFunction/samples/blob/main/functions/tracing/README.md
> 
> pls let me know if it can solve your problem, thx.

nice
