### ISSUE TITLE
[Feature] Support init container in OpenFunction

### ISSUE THREAD

**Issue by lizzzcai** [OpenFunction/OpenFunction#257]
**Description**
To support init containers in `Function`.

Use cases:
1. in AI use cases, init container can help to download models
2. inject secret from remote https://github.com/knative/serving/issues/4307#issuecomment-777115722

**Comment by lizzzcai** [comment]
Init containers and PVC are supported in Knative v1.2 [features](https://github.com/knative/serving/blob/release-1.2/config/core/configmaps/features.yaml#L148-L161). But still in [Alpha](https://github.com/knative/serving/issues/12438), and to use knative v1.2, kubernetes must be v1.21+. (is openfunction supporting knative v1.2 and kubernetes v1.21+?) Otherwise probably need to use webhook to inject it. 

For KEDA probably don't have such limitation.

**Comment by benjaminhuo** [comment]
With the new ofn cli, it is possible to decouple OpenFunction with its dependencies like knative.
So what we need to do is to test the compatibility of OpenFunction with Knative v1.2.

@tpiperatgod Am I correct?

**Comment by tpiperatgod** [comment]
> With the new ofn cli, it is possible to decouple OpenFunction with its dependencies like knative. So what we need to do is to test the compatibility of OpenFunction with Knative v1.2.
> 
> @tpiperatgod Am I correct?

Yes, it is currently possible to install a specific version of the component through ofn. Pls refer to this: https://github.com/OpenFunction/cli/blob/main/docs/install.md#customize-component-version

**Comment by lizzzcai** [comment]
I have tried out KNative `v1.2`, and it is working fine in ofn `v0.6`. Users need to enable the feature manually: https://knative.dev/v1.2-docs/serving/configuration/feature-flags/#kubernetes-init-containers.

**Comment by benjaminhuo** [comment]
Close this for now because knative supports init container itself without the need to modification to openfunction
