### ISSUE TITLE
Project proposal: OpenFunction CLI

### ISSUE THREAD

**Issue by tpiperatgod** [OpenFunction/OpenFunction#29]
# Abstract

OpenFunction requires a command line tool to manage itself and its associated resources.

This command line tool will have the following features:

- A more elegant way to display logs and progress
  It can collect logs and events of OpenFunction's resources in kubernetes and display them after correlation processing.
- Targeted resource manipulation
  It will simplify the parameters so that functions can be easily constructed.
  And it will follow the business model and operate on the OpenFunction and its associated resources uniformly, not just on the OpenFunction itself.

# Cases

> In the case I assume that the CLI is called **```of```**

- Registry

  Create a Registry

  ```shell
  of registry create --name registry_demo --url "https://index.docker.io/v1/" --account some_account
  ```

- Builder

  Create a Builder

  ```shell
  of builder create --name builder_demo --builder somebuilder --src https://github.com/OpenFunction/function-samples.git --subpath hello-world-go --image "<your registry name>/sample-go-func:latest" --registry registry_demo
  ```

- Serving

  Create a Serving

  ```shell
  of serving create --name serving_demo --runtime Knative
  ```

- Function

  Create a Function

  ```shell
  of function create --name function_demo --build builder_demo --serving serving_demo --version v1.0.0
  ```

  Describe a Function(just reference ```tkn```)

  ```shell
  Name:              function_demo
  Namespace:         default
  Builder Ref:       builder_demo
  Serving Ref:       serving_demo
  Registry Account:  registry_demo
  Timeout:           1h0m0s
  
  🌡️  Status
  
  STARTED          DURATION   STATUS
  23 seconds ago   ---        Running
  
  📦 Resources
  
   No resources
  
  ⚓ Params
  
   No params
  
  📝 Results
  
   No results
  
  🗂  Taskruns
  
   NAME              TASK NAME               STARTED          DURATION   STATUS
   ∙ function-demo   function-demo-task-1    23 seconds ago   ---        Running
  ```

**Comment by benjaminhuo** [comment]
of could be changed to `fn` or `func`
You can write a proposal like https://github.com/thanos-io/thanos/tree/main/docs/proposals and submit a PR

**Comment by tpiperatgod** [comment]
Ok, I'll reorganize the proposal later
