### ISSUE TITLE
Can we parse some parameters in function definition yaml to control the build behaviors?

### ISSUE THREAD

**Issue by zylan29** [OpenFunction/OpenFunction#294]
Can we parse some parameters in function definition yaml to control the build behaviors?

For example: 
A parameter for Python to specify a faster pypi repo: `pip install -I https://<a-faster-pypi-repo>`
A environment variable `GIT_SSL_NO_VERIFY`  for git to ignore https cert verification.

**Comment by benjaminhuo** [comment]
You can set environment variable like this https://github.com/OpenFunction/samples/blob/main/functions/async/logs-handler-function/logs-handler-function.yaml#L16

**Comment by zylan29** [comment]
Hi @benjaminhuo , Thanks,  I found some useful info in `https://github.com/OpenFunction/gcp-builder/blob/main/README.md`, cheers.
