### ISSUE TITLE
Upgrade yaml.v2 to yaml.v3 to fix CVE

### ISSUE THREAD

**Issue by benjaminhuo** [OpenFunction/OpenFunction#298]
**Description**
CVE detected: https://github.com/OpenFunction/OpenFunction/security/dependabot/1
We need to fix this manually by upgrading gopkg.in/yaml.v2 to gopkg.in/yaml.v3

**Additional context**
![Snip20220530_211](https://user-images.githubusercontent.com/18525465/170909303-f8205e5e-3fc7-4f58-8d2c-ddea75c40a48.png)

**Comment by Aarush-Goyal** [comment]
@benjaminhuo I would like to fix this issue

**Comment by benjaminhuo** [comment]
Great! @Aarush-Goyal

**Comment by Aarush-Goyal** [comment]
@benjaminhuo to which branch should I make the pull request to?
