### ISSUE TITLE
Can change evnet source handler && trigger handler image repo to private image repo

### ISSUE THREAD

**Issue by shyupc** [OpenFunction/OpenFunction#353]
**Description**
We try to use event framework to trigger a function，all env in an internal network。But the event controller make eventsource handler image to a constant value。Can make the image value read from Open Function Controller pod env or configmap else？

**Comment by benjaminhuo** [comment]
It's a good requirement, would you like to create a PR for this? @shyupc 
If not, we can fix this later @wrongerror
