### ISSUE TITLE
Slack link in readme is not working

### ISSUE THREAD

**Issue by KlausMikhaelson** [OpenFunction/OpenFunction#355]
**Description**
Slack link in the readme is not working 

**Environmental**
Tell us what your cluster environment is like, e.g.

- Operating System Information
- kubernetes version
- OpenFunction version
- Versions of dependent components (e.g. dapr, keda, shipwright, knative)

**Expected behavior**
It should redirect to the slack channel

**Actual behavior**
Showing that the link is no longer active

**Screenshots**
<img width="718" alt="image" src="https://user-images.githubusercontent.com/100528412/186253823-bfb5bd3c-999c-4b9e-8b1f-cdba9f117364.png">

**Comment by KlausMikhaelson** [comment]
If it'll get approved than would like to work on it

**Comment by benjaminhuo** [comment]
@KlausMikhaelson Where do you find the broken link? The slack link in readme is moved to https://github.com/OpenFunction/community#contact-us

**Comment by KlausMikhaelson** [comment]
it's here 
<img width="735" alt="image" src="https://user-images.githubusercontent.com/100528412/186336557-4fdee25a-823d-479a-98bb-7c79044ed233.png">

**Comment by benjaminhuo** [comment]
@KlausMikhaelson good catch! Yeah, it'll be good if you can help to change that!
Thanks

**Comment by KlausMikhaelson** [comment]
Thank you @benjaminhuo would love to make that change and make my first contribution in this community but since it's my first time I am not in the slack channel so can you please add the correct link of the channel here in the comments ?

**Comment by benjaminhuo** [comment]
You can find it here https://github.com/OpenFunction/community#contact-us

**Comment by KlausMikhaelson** [comment]
Yeah got it thank you !

**Comment by KlausMikhaelson** [comment]
Hey @benjaminhuo I am new in this domain so I used to contribute in web development before so I am not sure if we are supposed to install dependencies after cloning it so I just cloned it and made the changes and creating a pr can you please direct me to some documentation on it if there is any ? I have checked the one where it was showing that we just have to clone it and make the changes than create a branch and commit there but just a bit confused.
Thank you
