### ISSUE TITLE
When to enable dapr-proxy mode

### ISSUE THREAD

**Issue by wrongerror** [OpenFunction/OpenFunction#371]
Current logic:

- async function:
  - when "dapr.io/service-mode" is not "sidecar"  in  `serving.spec.annotations`.

- sync function:
  - when "dapr.io/service-mode" is not "sidecar"  in  `serving.spec.annotations` and `serving.spec.outputs` is not nil or `dapr.io/enabled` is true.
 
And also I didn't change the `serving.spec.annotations` of user configuration, just handle and set annotations when generating workload or ksvc.

Does this logic need to be optimized, and what are the suggestions?

**Comment by wrongerror** [comment]
Optimized logic:
- when "openfunction.io/enable-dapr" is "true" and "openfunction.io/dapr-service-mode" is "standalone", enable dapr-proxy.
- when "openfunction.io/enable-dapr" is "true" and "openfunction.io/dapr-service-mode" is "sidecar", enable dapr-sidecar.
- when "openfunction.io/enable-dapr" is "false", disable both dapr-proxy and dapr-sidecar.

The default value of annotations:
- when user does not defined "openfunction.io/enable-dapr" in `serving.spec.annotations`,  if user defined `serving.spec.inputs` or `serving.spec.outputs`, the value of this annotation will be treated as "true", otherwise it will be treated as "false".
- when user does not defined "openfunction.io/dapr-service-mode", the default value of this annotation is "standalone".

**Comment by benjaminhuo** [comment]
> Optimized logic:
> 
> * when "openfunction.io/enable-dapr" is "true" and "openfunction.io/dapr-service-mode" is "standalone", enable dapr-proxy.
> * when "openfunction.io/enable-dapr" is "true" and "openfunction.io/dapr-service-mode" is "sidecar", enable dapr-sidecar.
> * when "openfunction.io/enable-dapr" is "false", disable both dapr-proxy and dapr-sidecar.
> 
> The default value of annotations:
> 
> * when user does not defined "openfunction.io/enable-dapr" in `serving.spec.annotations`,  if user defined `serving.spec.inputs` or `serving.spec.outputs`, the value of this annotation will be treated as "true", otherwise it will be treated as "false".
> * when user does not defined "openfunction.io/dapr-service-mode", the default value of this annotation is "standalone".

We need to put this logic into v0.8.0 docs
