### ISSUE TITLE
Create a secret page not found

### ISSUE THREAD

**Issue by sachinparihar** [OpenFunction/OpenFunction#389]
#### Description
When I open this page, showing that error!
link: https://openfunction.dev/docs/getting-started/your-first-function/function-go/#create-a-secret

<img width="953" alt="Screenshot 2022-11-18 215333" src="https://user-images.githubusercontent.com/94243074/202752841-963fd8f6-8589-4b60-80a0-6a8e131a7382.png">

**Comment by benjaminhuo** [comment]
> link: https://openfunction.dev/docs/getting-started/your-first-function/function-go/#create-a-secret

@sachinparihar where do you find this link? The docs have been revised and the `your first function` section no longer exists anymore.

You can find the new guide here
https://openfunction.dev/docs/getting-started/quickstarts/

**Comment by sachinparihar** [comment]
Hi! @benjaminhuo, I found this error at best practices `Create a Knative-based Function to Interact with Middleware` section, when I click Prerequisites `created a secret`, the above error appers
https://openfunction.dev/docs/best-practices/interact-with-dapr-output-binding/

**Comment by benjaminhuo** [comment]
@sachinparihar would you help to change it to https://openfunction.dev/docs/getting-started/quickstarts/prerequisites/  in https://github.com/OpenFunction/openfunction.dev ?

**Comment by sachinparihar** [comment]
Yes
