### ISSUE TITLE
Delete service when function is deleted

### ISSUE THREAD

**Issue by B1F030** [OpenFunction/OpenFunction#484]
**Description**
In current version of OpenFunction(v1.1), when an async function is deleted, the relative service will not be removed.

**Screenshots**
![59c93c549c2fcee9281a17f77718694](https://github.com/OpenFunction/OpenFunction/assets/77265354/fbe391e5-4eec-4785-b676-188aa817f63d)

**Improvement**
Therefore, I propose to add service delete logic in [async/servingrun.go](https://github.com/OpenFunction/OpenFunction/blob/main/pkg/core/serving/openfuncasync/servingrun.go) like this:
![image](https://github.com/OpenFunction/OpenFunction/assets/77265354/b2f4147e-162c-4a76-a2bc-26aeb0744e85)

**Comment by benjaminhuo** [comment]
@wanjunlei @wrongerror what do you think?

**Comment by B1F030** [comment]
#https://github.com/OpenFunction/OpenFunction/pull/483
