### ISSUE TITLE
OpenFunction 1.20  install  fail

### ISSUE THREAD

**Issue by xuybin** [OpenFunction/OpenFunction#500]
**Description**
install fail.

**Environmental**
Tell us what your cluster environment is like, e.g.

- Operating System Information
- Kubernetes v1.27.3
- OpenFunction 1.20
- Versions of dependent components (e.g. dapr, keda, shipwright, knative)

**Expected behavior**
install ok.

**Actual behavior**
Tell us what happens instead. Provide a log message if relevant.

**To Reproduce**
  1. helm repo add openfunction https://openfunction.github.io/charts/
  2. helm repo update
  3. kubectl create namespace openfunction
  4. helm install openfunction openfunction/openfunction -n openfunction --debug
  5. root@ai-pc:~#   helm install openfunction openfunction/openfunction -n openfunction --debug
install.go:192: [debug] Original chart version: ""
install.go:209: [debug] CHART PATH: /root/.cache/helm/repository/openfunction-v1.2.0-v0.7.0.tgz

client.go:128: [debug] creating 1 resource(s)
install.go:151: [debug] CRD builders.core.openfunction.io is already present. Skipping.
client.go:128: [debug] creating 1 resource(s)
install.go:151: [debug] CRD clustereventbuses.events.openfunction.io is already present. Skipping.
client.go:128: [debug] creating 1 resource(s)
install.go:151: [debug] CRD eventbuses.events.openfunction.io is already present. Skipping.
client.go:128: [debug] creating 1 resource(s)
install.go:151: [debug] CRD eventsources.events.openfunction.io is already present. Skipping.
client.go:128: [debug] creating 1 resource(s)
install.go:151: [debug] CRD functions.core.openfunction.io is already present. Skipping.
client.go:128: [debug] creating 9 resource(s)
install.go:151: [debug] CRD gatewayclasses.gateway.networking.k8s.io is already present. Skipping.
client.go:128: [debug] creating 1 resource(s)
install.go:151: [debug] CRD gateways.networking.openfunction.io is already present. Skipping.
client.go:128: [debug] creating 1 resource(s)
install.go:151: [debug] CRD servings.core.openfunction.io is already present. Skipping.
client.go:128: [debug] creating 1 resource(s)
install.go:151: [debug] CRD triggers.events.openfunction.io is already present. Skipping.
client.go:128: [debug] creating 1 resource(s)
install.go:151: [debug] CRD components.dapr.io is already present. Skipping.
client.go:128: [debug] creating 1 resource(s)
install.go:151: [debug] CRD configurations.dapr.io is already present. Skipping.
client.go:128: [debug] creating 1 resource(s)
install.go:151: [debug] CRD httpendpoints.dapr.io is already present. Skipping.
client.go:128: [debug] creating 1 resource(s)
install.go:151: [debug] CRD resiliencies.dapr.io is already present. Skipping.
client.go:128: [debug] creating 1 resource(s)
install.go:151: [debug] CRD subscriptions.dapr.io is already present. Skipping.
client.go:128: [debug] creating 12 resource(s)
install.go:151: [debug] CRD certificates.networking.internal.knative.dev is already present. Skipping.
client.go:128: [debug] creating 1 resource(s)
install.go:151: [debug] CRD clustertasks.tekton.dev is already present. Skipping.
client.go:128: [debug] creating 1 resource(s)
install.go:151: [debug] CRD pipelines.tekton.dev is already present. Skipping.
client.go:128: [debug] creating 1 resource(s)
install.go:151: [debug] CRD pipelineresources.tekton.dev is already present. Skipping.
client.go:128: [debug] creating 1 resource(s)
install.go:151: [debug] CRD pipelineruns.tekton.dev is already present. Skipping.
client.go:128: [debug] creating 1 resource(s)
install.go:151: [debug] CRD resolutionrequests.resolution.tekton.dev is already present. Skipping.
client.go:128: [debug] creating 1 resource(s)
install.go:151: [debug] CRD runs.tekton.dev is already present. Skipping.
client.go:128: [debug] creating 1 resource(s)
install.go:151: [debug] CRD tasks.tekton.dev is already present. Skipping.
client.go:128: [debug] creating 1 resource(s)
install.go:151: [debug] CRD taskruns.tekton.dev is already present. Skipping.
client.go:128: [debug] creating 1 resource(s)
install.go:151: [debug] CRD builds.shipwright.io is already present. Skipping.
client.go:128: [debug] creating 1 resource(s)
install.go:151: [debug] CRD buildruns.shipwright.io is already present. Skipping.
client.go:128: [debug] creating 1 resource(s)
install.go:151: [debug] CRD buildstrategies.shipwright.io is already present. Skipping.
client.go:128: [debug] creating 1 resource(s)
install.go:151: [debug] CRD clusterbuildstrategies.shipwright.io is already present. Skipping.
W0924 04:08:15.131383   42824 warnings.go:70] The v1alpha2 version of Gateway has been deprecated and will be removed in a future release of the API. Please upgrade to v1beta1.
W0924 04:08:15.135596   42824 warnings.go:70] The v1alpha2 version of GatewayClass has been deprecated and will be removed in a future release of the API. Please upgrade to v1beta1.
Error: INSTALLATION FAILED: create: failed to create: Secret "sh.helm.release.v1.openfunction.v1" is invalid: data: Too long: must have at most 1048576 bytes
helm.go:84: [debug] **Secret "sh.helm.release.v1.openfunction.v1" is invalid: data: Too long: must have at most 1048576 bytes**
create: failed to create
helm.sh/helm/v3/pkg/storage/driver.(*Secrets).Create
        helm.sh/helm/v3/pkg/storage/driver/secrets.go:164
helm.sh/helm/v3/pkg/storage.(*Storage).Create
        helm.sh/helm/v3/pkg/storage/storage.go:69
helm.sh/helm/v3/pkg/action.(*Install).RunWithContext
        helm.sh/helm/v3/pkg/action/install.go:340
main.runInstall
        helm.sh/helm/v3/cmd/helm/install.go:278
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:139
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.5.0/command.go:872
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.5.0/command.go:990
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.5.0/command.go:918
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:250
runtime.goexit
        runtime/asm_amd64.s:1571
INSTALLATION FAILED
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:141
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.5.0/command.go:872
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.5.0/command.go:990
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.5.0/command.go:918
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:250
runtime.goexit
        runtime/asm_amd64.s:1571

**Screenshots**
![image](https://github.com/OpenFunction/OpenFunction/assets/10354549/46cfb733-ca04-44f4-8507-b8b69dfcab3f)

**Additional context**

**Comment by wrongerror** [comment]
The cause of this issue is that the CRDs contain a lot of description, which causes the helm release to exceed the limit. Try to execute `helm repo update` and reinstall.

**Comment by xuybin** [comment]
After executing helm repo update, it's normal
```root@ai-pc:~# helm list -n openfunction
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
openfunction    openfunction    1               2023-09-24 15:54:06.4210719 +0800 CST   deployed        openfunction-0.7.0      1.2.0
root@ai-pc:~#
```
