### ISSUE TITLE
OpenFunction website Initiation

### ISSUE THREAD

**Issue by FeynmanZhou** [OpenFunction/OpenFunction#81]
After we discussed the website initiation in our community call, we are going to use a Hugo template [Docsy](https://github.com/google/docsy) to build the OpenFunction website from scratch. 

Proposed steps:
1. Create a new GitHub repo for this website in [OpenFunction Org](https://github.com/OpenFunction).
2. Initiate the website framework.
3. Make it accessible, we can preview it locally or access it from the internet.
4. Adjust the style and design to be aligned with the OpenFunction.
5. Migrate the content to the website.

**Comment by FeynmanZhou** [comment]
Please also help to add the instruction in the [README](https://github.com/OpenFunction/website), see [KubeSphere website](https://github.com/kubesphere/website#kubesphere-website) as an example.

**Comment by benjaminhuo** [comment]
We can close this issue now? @FeynmanZhou

**Comment by FeynmanZhou** [comment]
Yes.
