### ISSUE TITLE
Add a todo list for OpenFunction events framework

### ISSUE THREAD

**Issue by tpiperatgod** [OpenFunction/OpenFunction#87]
In PR #83 we set up the basic OpenFunction events framework. There are still some refinement work and feature development tasks that we need to complete.

**What can it currently do**
- Ability to handle NATS streaming type EventBus
- Ability to handle Redis, Kafka, Cron(scheduler) type EventSources
- EventSources can trigger Knative Service synchronization calls
- The EventSource can send events to the EventBus(or ClusterEventBus)
- Triggers can associate EventBus(or ClusterEventBus) and then trigger target functions (including Knative Service function and OpenFuncAsync function)

**TODO:**
- [x] #88

- [x] #97

- [x] #98

- [x] #124

- [ ] Add more kinds of event sources, event buses, triggers

- [x] Add samples && concept docs

**Comment by tpiperatgod** [comment]
For the task "Add samples && concept docs", I have added the relevant documentation: [OpenFunction Events Framework](https://github.com/OpenFunction/OpenFunction/blob/main/docs/concepts/OpenFunction-events-framework.md)

**Comment by benjaminhuo** [comment]
> OpenFunction Events Framework

It's better to add a link to this doc in the README

**Comment by benjaminhuo** [comment]
> For the task "Add samples && concept docs", I have added the relevant documentation: [OpenFunction Events Framework](https://github.com/OpenFunction/OpenFunction/blob/main/docs/concepts/OpenFunction-events-framework.md)

@tpiperatgod It's better to add a link to this doc in the README

**Comment by tpiperatgod** [comment]
> > For the task "Add samples && concept docs", I have added the relevant documentation: [OpenFunction Events Framework](https://github.com/OpenFunction/OpenFunction/blob/main/docs/concepts/OpenFunction-events-framework.md)
> 
> @tpiperatgod It's better to add a link to this doc in the README

Okay, I will find a suitable place to add it.

**Comment by tpiperatgod** [comment]
Since we have completed the main part of the events framework, I think we can close this issue. 

And the work of enriching and improving the events framework can be tracked by opening a separate issue according to the specific content and requirements.

**Comment by benjaminhuo** [comment]
> Since we have completed the main part of the events framework, I think we can close this issue.
> 
> And the work of enriching and improving the events framework can be tracked by opening a separate issue according to the specific content and requirements.

Agree
